#include <stdio.h>
#include <stdlib.h>

int main() {
	int i, j, k, t;
	char a[50][50]={0,};
	scanf("%d", &t);
	for(i=0;i<t;i++)
	{
		scanf("%s", &a[i]);
	}
	for(i=t-1;i>0;i--)
	{
		for(j=0;j<t;j++)
		{
			if(a[i][j]%62==1)
			{
				if(j==0&&a[i][j-1]%62!=1)
				{
						if(a[i][j+1]>a[i+1][j])
						{
							a[i][j]=(a[i+1][j]+10)-a[i][j+1]+48;
						}
						else
						{
							a[i][j]=a[i+1][j]-a[i][j+1]+48;
						}
				}
				if(0<j&&(t-i-1)>j)
				{
					if(a[i][j+1]%62==1)
					{
						if(a[i][j-1]>a[i+1][j-1])
						{
							a[i][j]=(a[i+1][j-1]+10)-a[i][j-1]+48;
						}
						else
						{
							a[i][j]=a[i+1][j-1]-a[i][j-1]+48;
						}
					}
					if(a[i][j-1]%62==1)
					{
						if(a[i][j+1]>a[i+1][j])
						{
							a[i][j]=(a[i+1][j]+10)-a[i][j+1]+48;
						}
						else
						{
							a[i][j]=a[i+1][j]-a[i][j+1]+48;
						}
					}
				}
				if(j==t-i-1&&a[i][j-1]%62!=1)
				{
					if(a[i][j-1]>a[i+1][j-1])
						{
							a[i][j]=(a[i+1][j-1]+10)-a[i][j-1]+48;
						}
						else
						{
							a[i][j]=a[i+1][j-1]-a[i][j-1]+48;
						}
				}
			}
		}
		for(j=t-i-1;j>-1;j--)
		{
			if(a[i][j]%62==1)
			{
				if(j==0)
				{
						if(a[i][j+1]>a[i+1][j])
						{
							a[i][j]=(a[i+1][j]+10)-a[i][j+1]+48;
						}
						else
						{
							a[i][j]=a[i+1][j]-a[i][j+1]+48;
						}
				}
				if(0<j&&(t-i-1)>j)
				{
					if(a[i][j+1]%62!=1)
					{
						if(a[i][j-1]>a[i+1][j-1])
						{
							a[i][j]=(a[i+1][j-1]+10)-a[i][j-1]+48;
						}
						else
						{
							a[i][j]=a[i+1][j-1]-a[i][j-1]+48;
						}
					}
					else
					{
						if(a[i][j+1]>a[i+1][j])
						{
							a[i][j]=(a[i+1][j]+10)-a[i][j+1]+48;
						}
						else
						{
							a[i][j]=a[i+1][j]-a[i][j+1]+48;
						}
					}
				}
				if(j==t-i-1)
				{
					if(a[i][j-1]>a[i+1][j-1])
						{
							a[i][j]=(a[i+1][j-1]+10)-a[i][j-1]+48;
						}
						else
						{
							a[i][j]=a[i+1][j-1]-a[i][j-1]+48;
						}
				}
			}
		}
		
	}
	for(i=0;i<t;i++)
	{
		printf("%s\n", a[i]);
	}
	return 0;
}
