#홈페이지에서 API서비스 신청시 받은 Appkey, Appsecret 값 설정
APP_KEY: "PSMpPfJkOrhVc95Gp9VCSEOTS6HLd16hW0mq"
APP_SECRET: "LwOPYoZOx/VPWfYZ0TT6yVRnLQhubEGbFGeNH7UgPnVOMQd/CZJMMo10jg7t/k0mqu0+Pfj/zYYa/VfdQDsq213jYnIHBAJXI5BndZcdPadFWy5I2D/RHfa3odeSAxmvbOslpOibeJQ9CoC6yQnuyOGhxZDMgqbd+VxEJ8t/WJUHMpw+Meo="

#계좌번호 앞 8자리
CANO: "50077050"
#계좌번호 뒤 2자리
ACNT_PRDT_CD: ""

#실전투자
#URL_BASE: "https://openapi.koreainvestment.com:9443"
#모의투자
URL_BASE: "https://openapivts.koreainvestment.com:29443"

#디스코드 웹훅 URL
DISCORD_WEBHOOK_URL: "https://discordapp.com/api/webhooks/1050290839437455432/Mk6rAr60WBX4LLwOq3jaXorG_ZI4QCeHzkbJoKZMbTAYEHYvNCggKp7N3H3VJe6yM4Ib"